import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import "./globals.css";
import NavBar from "@/components/NavBar";

import { Provider } from "@/components/Provider";
import DStar from "@/components/DStar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Fateh's Protfolio",
  description: "Generated by Fateh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-[#121212] bg-slate-200 transition duration-300">
        <Provider>
          <NavBar />
          {children}
          <SpeedInsights />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
